### ISSUE TITLE
ViewController never gets removed

### ISSUE THREAD

**Issue by szhrmp** [zendeskarchive/FSVerticalTabBarController#11]
setSelectedIndex is broken, the variable selectedIndex is defined as unsigned integer, but you actually assign it -1 and assume it is a signed integer.

e.g. line 95:  if (-1 < _selectedIndex && _selectedIndex < INT_MAX)
is never true as -1 gets converted to an unsigned type and is bigger than the selectedIndex

I suggest converting selectedIndex to a NSInteger. this requires that lines like 82 are change to:

if (selectedIndex != _selectedIndex && selectedIndex < (int)[self.viewControllers count])

eg. an additional (int) cast is required

**Comment by bejo** [comment]
Thanks for finding this bug and suggesting the fix. I the end I decided to stick with NSUInteger in order to follow UITabBarController conventions. I'd love get your opinion on my fix: https://github.com/futuresimple/FSVerticalTabBarController/commit/d5104a68e8506d935d396394cf3bee9ed2c16959
