### ISSUE TITLE
Change the height for a cell

### ISSUE THREAD

**Issue by KaushiKularatnam** [zendeskarchive/FSVerticalTabBarController#12]
I added a different image than the selectionindicator image thats provided in each of the tableview cells. However the image gets cropped from the top. I tried adjusting the tabbarbutton class but that doesnt work. Does anyone know how to increate the height or the cell? The usual method rowheight doesnt work. Or any way in which i can display the full image. Thanks

**Comment by bejo** [comment]
Change DEFAULT_ITEM_HEIGHT in FSVerticalTabBar.m
