### ISSUE TITLE
Tab Bar Gradient Drawing

### ISSUE THREAD

**Issue by jstart** [zendeskarchive/FSVerticalTabBarController#2]
Per the initial README by Future Simple, it would be great to enable gradient backgrounds on the tab bar.  Setting up this issue to track discussion regarding the milestone of adding this feature.

**Comment by bejo** [comment]
I should be able to work on this and other issues on Thursday afternoon.
BTW: if anyone's at Krakow this week, come to HackKrk on Thursday http://hackkrk.com/ :)

**Comment by bejo** [comment]
Done: https://github.com/futuresimple/FSVerticalTabBarController/commit/d93771db1c0b6ce5d5e08de3bd3a912b16950653 :)
