### ISSUE TITLE
Mac Support

### ISSUE THREAD

**Issue by jstart** [zendeskarchive/FSVerticalTabBarController#3]
It would be awesome to make a unified API for a vertical tab bar that works one iPhone/iPad/Mac OSX.  I think this would make FSVerticalTabBarController stand out from our arch nemesis:
https://github.com/NOUSguide/NGTabBarController

:P

**Comment by bejo** [comment]
Wow, I didn't know about NGTabBarController! I guess it won't hurt to have two nice controls for tab bar navigation on iOS :)

About Mac support, I'm not a big fun of transferring UI from iOS to OS X (yet! maybe in mouton lion...). Anyway, if someone can pull that off, why not!
